### ISSUE TITLE
Divide app.py into appropriate scripts

### ISSUE THREAD

**Issue by ayushprd** [The-Open-Source-Club/Event_Management_WebApp#1]
Currently, [`app.py`](https://github.com/The-Open-Source-Club/Event_Management_WebApp/blob/master/app.py) has the entire logic for the app. It would be a better design if it was divided into different sections in separate files. For example, `search.py` can be created for containing the search route and the logic which can then be imported in `app.py`.

**Comment by AstroKiR** [comment]
Can I help you to solve this problem?

**Comment by ayushprd** [comment]
Yes, that would be great @AstroKiR For starting you can begin with the search example mentioned in the issue.

**Comment by vallabhiaf** [comment]
Can i help ?

**Comment by ayushprd** [comment]
Fixed in #2 and #5
